name: Red Hat JBoss BPM Suite
abbreviated_name: JBoss BPM Suite
has_installer: true
current_version: 6.2.0.GA
documentation_minor_version: 6.2
xpaas_url: https://www.openshift.com/developers/jboss-bpms
intro_video: https://vimeo.com/142883902
vimeo_album: http://vimeo.com/album/2982446
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKphPQWLX8SPJlPyqDhpZS4U
skip_installation_instructions: true
skip_maven_instructions: true
buzz_tags:
  - bpm suite
  - jbpm
  - jbossbpmsuite
  - bpm
  - BPM Suite
guides:
  Release_Notes:
  Administration_And_Configuration_Guide:
  Business_Resource_Planner_Guide:
  Development_Guide:
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:
default_download_artifact_type: installer
description: 'A business process and decision management platform that provides business users and developers with powerful and intuitive tools to capture business processes, policies and rules.  Combined with reporting and simulation, this platform allows agile modification of systems in response to business needs.'
upstream_projects:
  - drools
  - guvnor
  - optaplanner
  - jbpm
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_bpmsuite.png
    url: /quickstarts/brms/tasks-bpmsuite
