name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
current_version: 9.1.0.GA
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKrxJ9OtX2Zmgw3nyeYs0QGR
buzz_tags:
  - jbds
guides:
  Release_Notes:
  Install_Red_Hat_JBoss_Developer_Studio:
  Update_Red_Hat_JBoss_Developer_Studio:
default_download_artifact_type: jar_universal
description: 'A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.'
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627

